"""
VerifyPulse Daily Misinformation Report Generator
Uses Claude API to summarise today's low-confidence stories into a readable report.
"""

import os
import json
import httpx
from datetime import datetime
from typing import Optional

ANTHROPIC_API_URL = "https://api.anthropic.com/v1/messages"
ANTHROPIC_MODEL = "claude-sonnet-4-20250514"
LOW_CONFIDENCE_THRESHOLD = 40.0

REPORT_SYSTEM_PROMPT = """You are a fact-checking analyst writing a daily misinformation report.
You will receive a list of low-confidence news stories.
Write a concise, professional report in markdown format.

Structure:
- Brief intro (1-2 sentences)
- One bullet per story: story title, why it's low confidence, what to watch for
- Brief closing note

Keep it under 300 words. Be neutral and factual. No alarmism."""


def generate_daily_report(clusters: list[dict]) -> dict:
    """
    Generate daily misinformation report from low-confidence clusters.

    Args:
        clusters: All scored clusters for today

    Returns:
        Dict with markdown report, story list, and metadata
    """
    low_confidence = [
        c for c in clusters
        if c.get("confidence_score", 100) < LOW_CONFIDENCE_THRESHOLD
    ]

    if not low_confidence:
        return {
            "date": datetime.now().strftime("%Y-%m-%d"),
            "story_count": 0,
            "summary": "No low-confidence stories detected today.",
            "stories": [],
            "markdown": "# VerifyPulse Daily Report\n\nNo disputed stories detected today. ✓",
        }

    stories_for_prompt = [
        {
            "title": c["title"],
            "confidence_score": c.get("confidence_score"),
            "confidence_label": c.get("confidence_label"),
            "source_count": c.get("source_count"),
            "regions": c.get("regions", []),
        }
        for c in low_confidence
    ]

    markdown = _generate_markdown_summary(stories_for_prompt)

    return {
        "date": datetime.now().strftime("%Y-%m-%d"),
        "story_count": len(low_confidence),
        "threshold": LOW_CONFIDENCE_THRESHOLD,
        "summary": f"{len(low_confidence)} low-confidence stories detected.",
        "stories": stories_for_prompt,
        "markdown": markdown,
    }


def _generate_markdown_summary(stories: list[dict]) -> str:
    """Call Claude to generate natural language report."""
    api_key = os.environ.get("ANTHROPIC_API_KEY", "")

    if not api_key:
        # Fallback: generate basic markdown without Claude
        return _fallback_markdown(stories)

    stories_text = json.dumps(stories, indent=2)

    try:
        response = httpx.post(
            ANTHROPIC_API_URL,
            headers={
                "x-api-key": api_key,
                "anthropic-version": "2023-06-01",
                "content-type": "application/json",
            },
            json={
                "model": ANTHROPIC_MODEL,
                "max_tokens": 1000,
                "system": REPORT_SYSTEM_PROMPT,
                "messages": [
                    {
                        "role": "user",
                        "content": f"Generate a daily misinformation report for these stories:\n\n{stories_text}"
                    }
                ],
            },
            timeout=30.0,
        )
        response.raise_for_status()
        return response.json()["content"][0]["text"]

    except Exception as e:
        print(f"  [WARN] Report generation failed: {e}, using fallback")
        return _fallback_markdown(stories)


def _fallback_markdown(stories: list[dict]) -> str:
    """Generate basic markdown report without Claude API."""
    date_str = datetime.now().strftime("%d %B %Y")
    lines = [
        f"# VerifyPulse Daily Report — {date_str}",
        "",
        f"**{len(stories)} low-confidence stories** detected today requiring attention.",
        "",
        "## Disputed Stories",
        "",
    ]
    for s in stories:
        score = s.get("confidence_score", 0)
        label = s.get("confidence_label", "Unknown")
        sources = s.get("source_count", 0)
        lines.append(f"- **{s['title']}**")
        lines.append(f"  - Confidence: {score} ({label}) · {sources} source(s)")
        lines.append("")

    lines += [
        "---",
        "*Generated by VerifyPulse. Verify all stories with primary sources.*",
    ]
    return "\n".join(lines)